### ISSUE TITLE
Provide sort predicate based on class probability scores

### ISSUE THREAD

**Issue by vade** [Synopsis/Synopsis-Framework#43]
Would be nice to be able to use the global `SynopsisMetadataIdentifierVisualProbabilities` array to index into it based on a label string or possibly (and probably better) an enum of the class labels.

Sorting wouldn't be relative, but it would be based off of the confidence score of a particular concept.

We could in theory do similarity to 'concept groups' (ie, partials) as well, and match against other clips?

Something like

`+ (NSSortDescriptor*)sortViaSynopsisGlobalMetadataUsingConfidenceForClassLabel:(SynopsisMetadataClassLabel)label`

would let us pass in a ClassLabel enum and sort on the confidence score.

Or we could use something like 
`+ (NSSortDescriptor*)sortViaSynopsisGlobalMetadataUsingConfidenceForClassGroup:(SynopsisMetadataClassGroup)group relativeTo:(SynopsisMetadataItem*)item;`

The internal logic would could mask a dense feature, or return a sub matrix feature corresponding to the of labels. 

Label concepts would have to have adjacent/contiguous indices for sub-matrix selection. Masking would support non contiguous selection of probability scores, but would result in a 'sparse' matrix.

**Comment by vade** [comment]
@dlublin thoughts based on our convo?

**Comment by dlublin** [comment]
A good starting point would be the ability to get, for a given SynopsisMetadataItem and a given label (either as a string or an enum), to be able to get the probability for that label.

Once this is possible, creating any sort of ad-hoc sort descriptors / predicates (for general or specific use cases), or just displaying the info would be easy.

My initial thought was that I would like to make / have a method like, 
+ (NSSortDescriptor*)sortViaSynopsisGlobalMetadataUsingConfidenceForClassLabel:(SynopsisMetadataClassLabel)label;
but I may for example also want to show those confidence values as a column in the table view of results.

**Comment by vade** [comment]
So right now, you can get those confidence values by using the global dictionary and indexing into the dense feature for probabilities (the value for the enum / key SynopsisMetadataIdentifierVisualProbabilities).

The missing link is the mapping of class label to index, which the enum would solve.

**Comment by vade** [comment]
Oh to be clear, you can index and get an NSNumber out of a dense feature via `objectAtIndexedSubscript`

like 

`NSNumber*someConfidenceScore = globalProbabilityDenseFeature[someLabelIndex]`

**Comment by vade** [comment]
So one thing we can do to make this doable in a custom manner for now is to add an enum / typeDef for the labels. We can use the labels from the shipping model. The order should be correct for each group here:

https://github.com/Synopsis/CinemaNet/tree/master/Labels

And should be 'appended' in alphabetical order.

So it would be something like:

```
typedef NS_ENUM(NSUInteger, SynopsisMetadataPredictionClassLabel) {
color_key_blue = 0
color_key_green,
color_key_luma,
color_key_matte,
color_key_na,
color_saturation_saturated, 
color_saturation_pastel,
color_saturation_neutral, 
color_saturation_desaturated
...
};
```
and so forth but with nicer enum naming of course

**Comment by dlublin** [comment]
Yeah that would do the trick for now.

If the framework had a list of all possible labels in a pre-made array, you could look up a string by index in there, and its enum would be the same as the index.

Are the labels already in alphabetical order in the dense feature, or is this something that would require re-analyzing media?

**Comment by vade** [comment]
They are except for the last entry which is n/a but we can’t rely on alphabetical order estimate  in the future so I think enum works 

   
   

 http://vade.info

**Comment by vade** [comment]
Check out commits 33b231c9fa977806804874784bc97b94591ba774, 108ca7343bb3a66b5ac26fbca50c07a1ab907174, 85e47e0df870cff7add66b801b20cd2422119a82, cb56c05d1b3dbc9f302e1bbc0542b07e60bcee69, f34666e9f364f8663aaff77a525d9680ca0f7475, 

Note that in an earlier commit I fixed a bug that had us dropping one whole set of predictions (color key) so old analyzed content needs to - once again - be analyzed.

Note the above commits have yet to be tested at all haha
