### ISSUE TITLE
Case insensitive compare for description strings

### ISSUE THREAD

**Issue by dlublin** [Synopsis/Synopsis-Framework#8]
It'd be nice if [NSPredicate synopsisPredicateDescriptionContainsString:]  in NSPredicate+SynopsisMetadata.m used localizedCaseInsensitiveContainsString instead of containsString when doing comparisons.
(Or to have case insensitive compare as an alternative option)

**Comment by vade** [comment]
Oh good call!

**Comment by vade** [comment]
This actually opens up a question on how to localize / tokenize the tag/descriptions from the neural net, colors, etc in a meaningful way too - something I had been considering / thinking about for a bit.
